wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.34
    code_path: code/xw_mcts/main_bpp.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
alpha:
  desc: null
  value: 0.75
arenaCompare:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 64
binH:
  desc: null
  value: 10
binW:
  desc: null
  value: 10
cpuct:
  desc: null
  value: 1
cuda:
  desc: null
  value: true
dropout:
  desc: null
  value: 0.1
epStepThreshold:
  desc: null
  value: 100
epochs:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.001
maxlenOfQueue:
  desc: null
  value: 200000
numBins:
  desc: null
  value: 1
numEps:
  desc: null
  value: 50
numItems:
  desc: null
  value: 5
numIters:
  desc: null
  value: 500
numItersForTrainExamplesHistory:
  desc: null
  value: 200
numMCTSSims:
  desc: null
  value: 100
numScoresForRank:
  desc: null
  value: 250
num_channels:
  desc: null
  value: 256
seed:
  desc: null
  value: 100
updateThreshold:
  desc: null
  value: 0.6
